version: "3.9"

services:
  redis:
    container_name: face_recognition_redis
    restart: unless-stopped
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
